### Get all conversations for the authenticated user
GET http://localhost:3333/api/chats/conversations
Authorization: Bearer oat_NQ.a0M1a0FJa0NuSXA4QjlQOHlxY2xscGFRM1ZMbXAtREM3bWdld0IyUjE1MDI4MTQ3MzM

### Get all messages between authenticated user and another user
GET http://localhost:3333/api/chats?userId=2
Authorization: Bearer oat_NQ.a0M1a0FJa0NuSXA4QjlQOHlxY2xscGFRM1ZMbXAtREM3bWdld0IyUjE1MDI4MTQ3MzM

### Send a new message
POST http://localhost:3333/api/chats
Content-Type: application/json
Authorization: Bearer oat_NQ.a0M1a0FJa0NuSXA4QjlQOHlxY2xscGFRM1ZMbXAtREM3bWdld0IyUjE1MDI4MTQ3MzM

{
  "receiverId": 1,
  "message": "Hello, how much for the shoes?"
}

### Mark all messages from a user as read
POST http://localhost:3333/api/chats/mark-as-read
Content-Type: application/json
Authorization: Bearer oat_NQ.a0M1a0FJa0NuSXA4QjlQOHlxY2xscGFRM1ZMbXAtREM3bWdld0IyUjE1MDI4MTQ3MzM

{
  "userId": 2
}
