### Get all bank accounts for the authenticated user
GET http://localhost:3333/api/bank-accounts
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Create a new bank account
POST http://localhost:3333/api/bank-accounts
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "bankName": "Union Bank",
  "accountNumber": "1234567812",
  "homeAddress": "123 Main St, Lagos",
  "postalCode": "100001"
}

### Get a single bank account by ID
GET http://localhost:3333/api/bank-accounts/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Update a bank account by ID
PUT http://localhost:3333/api/bank-accounts/1
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "bankName": "GTBank",
  "accountNumber": "0987654321",
  "homeAddress": "456 New St, Abuja",
  "postalCode": "900001"
}

### Delete a bank account by ID
DELETE http://localhost:3333/api/bank-accounts/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk
