### Get all conversations for the authenticated user
GET http://localhost:3333/api/chats/conversations
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Get all messages between authenticated user and another user
GET http://localhost:3333/api/chats?userId=2
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Send a new message
POST http://localhost:3333/api/chats
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "receiverId": 1,
  "message": "Hello, how much for the shoes?"
}

### Mark all messages from a user as read
POST http://localhost:3333/api/chats/mark-as-read
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "userId": 2
}
