### Get all products
GET http://localhost:3333/api/products
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Create a new product
POST http://localhost:3333/api/products
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "productName": "Sample Product",
  "productLocation": "Lagos",
  "productStatus": "available",
  "listedBy": 1,
  "productPrice": 99.99,
  "productDetails": "A test product",
  "isFree": false,
  "isForSale": true,
  "categoryId": 1
}

### Create a new product with images
POST http://localhost:3333/api/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productName"

Sample Product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productLocation"

Lagos
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productStatus"

available
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="listedBy"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productPrice"

99.99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productDetails"

A test product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="isFree"

false
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="isForSale"

true
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="condition"

used
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="shipping.png"
Content-Type: image/png

< ./shipping.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="chat.png"
Content-Type: image/png

< ./chat.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### Get a product by ID
GET http://localhost:3333/api/products/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Update a product by ID
PUT http://localhost:3333/api/products/1
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "productName": "Updated Product Name",
  "productLocation": "Abuja",
  "productStatus": "sold",
  "listedBy": 1,
  "productPrice": 79.99,
  "productDetails": "Updated description",
  "isFree": false,
  "isForSale": true,
  "categoryId": 1
}

### Delete a product by ID
DELETE http://localhost:3333/api/products/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk
