### Get all reviews
GET http://localhost:3333/api/reviews
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Create a new review
POST http://localhost:3333/api/reviews
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "productId": 1,
  "userId": 1,
  "rating": 5,
  "comment": "Great product!"
}

### Get a review by ID
GET http://localhost:3333/api/reviews/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

### Update a review by ID
PUT http://localhost:3333/api/reviews/1
Content-Type: application/json
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk

{
  "rating": 4,
  "comment": "Updated review comment."
}

### Delete a review by ID
DELETE http://localhost:3333/api/reviews/1
Authorization: Bearer oat_MQ.Tm1wMUZRdWl3Y0dBR3NLMFVISGlmc0JXR25lZFRneXUtNllEQzUxMzExNjcwMzI1ODk
