### Get all wants
GET http://localhost:3333/api/wants
Authorization: Bearer oat_NDM.bVFUUmN5dVlSbXk3LXJzY2VDVjFBczRJSmFmaTJNRFg5NURVOGlmdDMzNTIyNjM0NDk

### Create a new want
POST http://localhost:3333/api/wants
Content-Type: application/json
Authorization: Bearer oat_NDM.bVFUUmN5dVlSbXk3LXJzY2VDVjFBczRJSmFmaTJNRFg5NURVOGlmdDMzNTIyNjM0NDk

{
  "name": "Phone",
  "keywords": ["phone", "electronics", "mobile"]
}

### Get a want by ID
GET http://localhost:3333/api/wants/1
Authorization: Bearer oat_NDM.bVFUUmN5dVlSbXk3LXJzY2VDVjFBczRJSmFmaTJNRFg5NURVOGlmdDMzNTIyNjM0NDk

### Update a want by ID
PUT http://localhost:3333/api/wants/1
Content-Type: application/json
Authorization: Bearer oat_NDM.bVFUUmN5dVlSbXk3LXJzY2VDVjFBczRJSmFmaTJNRFg5NURVOGlmdDMzNTIyNjM0NDk

{
  "name": "Updated want name",
  "keywords": ["updated", "keyword"],
  "userId": 1
}

### Delete a want by ID
DELETE http://localhost:3333/api/wants/1
Authorization: Bearer oat_NDM.bVFUUmN5dVlSbXk3LXJzY2VDVjFBczRJSmFmaTJNRFg5NURVOGlmdDMzNTIyNjM0NDk
